from django.urls import path
from . import views, seller_views, admin_views, password_reset_views

urlpatterns = [
    path('register/', views.register),
    path('register/seller/', views.register_seller),
    path('login/', views.login),
    path('password-reset/request/', password_reset_views.password_reset_request),
    path('password-reset/verify/', password_reset_views.password_reset_verify),
    path('password-reset/confirm/', password_reset_views.password_reset_confirm),
    path('me/', views.me),
    path('payment-card/', views.payment_card),
    path('orders/', views.orders_list),
    path('orders/create/', views.create_order),
    path('orders/<int:order_id>/review/', views.submit_review),
    path('orders/<int:order_id>/return/', views.submit_return),
    path('orders/<int:order_id>/cancel/', views.cancel_order),
    path('support/', views.support_ticket),
    path('analytics/visit/', admin_views.track_visit),
    path('seller/products/', seller_views.seller_products),
    path('seller/products/<int:product_id>/', seller_views.seller_product_detail),
    path('seller/orders/', seller_views.seller_orders),
    path('seller/orders/<int:order_id>/status/', seller_views.seller_order_status),
    path('seller/returns/', seller_views.seller_returns),
    path('seller/returns/<int:return_id>/', seller_views.seller_return_detail),
    path('seller/promotions/', seller_views.seller_promotions),
    path('seller/promotions/<int:promo_id>/', seller_views.seller_promotion_delete),
    path('seller/reports/sales/', seller_views.seller_sales_report),
    path('admin/tickets/', admin_views.admin_tickets),
    path('admin/tickets/<int:ticket_id>/close/', admin_views.admin_ticket_close),
    path('admin/products/pending/', admin_views.admin_product_submissions),
    path('admin/products/', admin_views.admin_products),
    path('admin/products/<int:product_id>/moderate/', admin_views.admin_product_moderate),
    path('admin/products/<int:product_id>/remove/', admin_views.admin_product_remove),
    path('admin/users/', admin_views.admin_users),
    path('admin/reviews/', admin_views.admin_reviews),
    path('admin/reviews/<int:review_id>/moderate/', admin_views.admin_review_moderate),
    path('admin/analytics/', admin_views.admin_analytics),
]
