import type { CSSProperties } from 'react';
import { COLORS } from '../../constants/colors';

export const authModalStyles: { [key: string]: CSSProperties } = {
  modalContainer: {
    position: 'fixed',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    backgroundColor: '#FFFFFF',
    width: 'min(420px, 92vw)',
    borderRadius: '16px',
    zIndex: 1101,
    boxShadow: '0 20px 40px rgba(78, 96, 83, 0.3)',
    animation: 'scaleUp 0.2s ease-out forwards',
    maxHeight: '90vh',
    overflowY: 'auto',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '20px 24px',
    borderBottom: `1px solid ${COLORS.border}`,
  },
  modalTitle: { margin: 0, fontSize: '20px', fontWeight: '800', color: COLORS.textDark },
  modalCloseButton: { background: 'none', border: 'none', fontSize: '18px', cursor: 'pointer', color: COLORS.textMuted },
  modalForm: { padding: '24px', display: 'flex', flexDirection: 'column', gap: '14px' },
  inputGroup: { display: 'flex', flexDirection: 'column', gap: '6px' },
  inputLabel: { fontSize: '12px', fontWeight: '600', color: COLORS.textMuted },
  modalInput: {
    padding: '11px 14px',
    borderRadius: '10px',
    border: `1px solid ${COLORS.border}`,
    fontSize: '14px',
    outline: 'none',
    backgroundColor: '#FAFBF9',
    width: '100%',
    boxSizing: 'border-box',
  },
  modalCheckboxRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  modalCheckboxLabel: { display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer' },
  checkbox: { accentColor: COLORS.primary, width: '16px', height: '16px' },
  checkboxText: { fontSize: '13px', color: COLORS.textMuted },
  forgotPassword: { fontSize: '13px', fontWeight: '600', color: COLORS.primary, cursor: 'pointer' },
  modalSubmitButton: {
    padding: '13px 0',
    borderRadius: '10px',
    border: 'none',
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: '15px',
    cursor: 'pointer',
    marginTop: '4px',
  },
  switchModalRow: { textAlign: 'center', fontSize: '13px', color: COLORS.textMuted, marginTop: '4px' },
  switchModalLink: { color: COLORS.primary, fontWeight: '700', cursor: 'pointer' },
  errorText: { color: '#FF4D4F', fontSize: '12px' },
  hintText: { fontSize: '12px', color: COLORS.textMuted, margin: 0 },
  popoverButton: {
    padding: '9px 0',
    borderRadius: '8px',
    fontSize: '13px',
    fontWeight: '700',
    cursor: 'pointer',
    border: 'none',
    width: '100%',
    transition: 'background-color 0.15s',
  },
};
